application: tensecondsofhappy
version: 1
runtime: python
api_version: 1

handlers:
    
- url: /stylesheets
  static_dir: stylesheets

- url: /assets
  static_dir: assets
  
- url: /assets/(.*)
  static_files: assets/\1
  upload: assets/(.*)
  
- url: /js
  static_dir: js

- url: /favicon.ico
  static_files: assets/favicon.ico
  upload: assets/favicon.ico

#- url: /html/(.*)
#  static_files: templates/\1
#  upload: templates/(.*)


- url: /admin/.*
  script: admin.py
  login: admin

- url: /ajax/.*
  script: ajax.py

- url: /.*
  script: main.py